### ISSUE TITLE
deleteAllIndexes method

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#11]
We could provide a `deleteAllIndexes` method.
This function is currently used in most of our SDKs but in the tests section. It's not a method provided for the users yet. 

### Behavior

Delete all the indexes.
If there is no index, it does nothing.

### Example (in PHP)

In the `Client` class:

```php
public function deleteAllIndexes()
{
    foreach ($this->getAllIndexes() as $index) {
        $this->deleteIndex($index['uid']);
    }
}
```

### Tests

- Test with no index
- Test with multiple indexes

### To do

- [x] Create an issue on each SDK repo and link it to this one  

Then, do it for:
- [ ] [Go](https://github.com/meilisearch/meilisearch-go/issues/23)
- [ ] [JS](https://github.com/meilisearch/meilisearch-js/issues/344)
- [x] [PHP](https://github.com/meilisearch/meilisearch-php/issues/27)
- [ ] [Python](https://github.com/meilisearch/meilisearch-python/issues/71)
- [ ] [Ruby](https://github.com/meilisearch/meilisearch-ruby/issues/30)
- [ ] [Swift](https://github.com/meilisearch/meilisearch-swift/issues/5)

**Comment by eskombro** [comment]
Yes! Yes, and yes!

**Comment by curquiza** [comment]
Need your approval @bidoubiwa so that I can pass it as `ready to implement` and start to create issues on each repo 😉

**Comment by bidoubiwa** [comment]
Yes !

**Comment by ppamorim** [comment]
The Swift library is totally async, including the delete functions, if I replicate the code above the SDK will trigger the deletion of doing one by one in a serial manner. What should happen if any of these indexes fail to delete? How the SDK should handle this?

**Comment by ppamorim** [comment]
I did something like this in the Swift library:

```swift
func deleteAll(_ completion: @escaping (Result<(), Swift.Error>) -> Void) {

    self.getAll { result in

        switch result {
        case .success(var indexes):

            var dispatch: ((Index) -> Void)!
            dispatch = { index in
                self.delete(index.UID) { result in
                    if indexes.isEmpty {
                        completion(.success(()))
                    } else {
                        dispatch(indexes.removeFirst())
                    }
                }
            }
            dispatch(indexes.removeFirst())

        case .failure(let error):
            completion(.failure(error))
        }

    }

}
```
This is Chaotically Evil! If any of the requests fail, it will be ignored by the script.

**Comment by curquiza** [comment]
@bidoubiwa Can you tell us if you would you have the same kind of issue with the JS library (because the methods are async in the JS SDK, right?)?

**Comment by ppamorim** [comment]
@curquiza Hi, is there any update on this?

**Comment by curquiza** [comment]
No, sorry, still waiting for @bidoubiwa (in vacation right now, we have to be patient 😇)

**Comment by bidoubiwa** [comment]
So this is an interesting question. Not only in synchronous languages

Imagine we try to delete the following list of indexes: `["one", "two", "three"]`

In sync libraries as this example in PHP 
```php
public function deleteAllIndexes()
{
    foreach ($this->getAllIndexes() as $index) {
        $this->deleteIndex($index['uid']);
    }
}
```
The calling stack will be the following : 
```
1.         $this->deleteIndex("one"); 
-- wait for meilisearch answer --  
2.         $this->deleteIndex("two"); 
-- wait for meilisearch answer --  
3.         $this->deleteIndex("three");
-- wait for meilisearch answer --  
```

Those 3 call are made to the same MeiliSearch instance. 
Now image a third party makes a call to that same MeiliSearch instance while this loop is running

```
1. phpSDK ->      $this->deleteIndex("one"); // wait for meilisearch answer
A. ThirdParty ->  delete index "two"
2. phpSDK ->      $this->deleteIndex("two");  // ERROR 404 thrown. Process stop here
3. phpSDK ->       $this->deleteIndex("three"); // never executed
```

#### Error throwing

By default with this way of writing the function, the process will stop at the first error thrown. So in a list of 3 indexes, if only the second fail, the third will not be deleted either.

Which is, I don't think, the expected behavior. Neither is it the good practice.

With some implementation the behavior could be different:

- Catch the error and continue the loop, this way index `three` is also deleted. But this mean that the user is **not aware that one delete failed**.

- Check before each delete that the index still exists, **but this is not bulletproof** since a third party could still delete the index between the check and the delete.

- Handle the error thrown based on the status code: 
    -> 404: This means the index is already deleted so no error should be thrown
    -> 400: Error in the request, process stop here and throw an error

Neither of these options is a good solution for a "database".
The best practice would have been that the function exists in MeiliSearch core and that it is handled with a [transaction](https://www.tutorialspoint.com/dbms/dbms_transaction.htm). Meaning that in a group of actions, if one action fails, all others are rolled-back to their original state. 

### Should this method be implemented in the SDK's

Imagine the implementation in javascript

```javascript
async function deleteAllIndexes()
{
  const indexes = await client.listIndexes();
  const deleteIndexes = await indexes.map(async (index) => {
    return client.getIndex(index.uid).deleteIndex()
  })
  return await Promise.all(deleteIndexes)
}
```

Imagine the same scenario where the index `two` is deleted by a third party. 
While the index `one` and index `three` are successfully deleted, the index two threw an error.

```
(node:12106) UnhandledPromiseRejectionWarning: MeiliSearchApiError: Index two not found
    at Index.<anonymous> (MeiliSearch/meilisearch-js/dist/bundles/meilisearch.cjs.js:256:39)
    ...
(Use `node --trace-warnings ...` to show where the warning was created)
```

If the user catches the error, index `one` and index `three` will still be deleted (the script ignores the error as in swift).
If the user does not catch the error, The process will continue without acting on the fact that an error was thrown (the script ignores the error and the user ignores it also). 

While reading the name of the method `deleteAllIndexes` it is not clear what you should expect. Most user will expect a transactional behavior, whereas if one index fail to delete, none are deleted. Others will expect the async behavior where the process tries to delete each index whether or not they fail and finally some, will expect the process to stop as soon as a error is thrown. In which case we must be clear on what has been deleted and what has not. 

I see the appeal in user-friendly languages like Ruby. Where I guess there is one expected way of doing it. But in other languages, as in js,  since this function is not clear on how it will react, and since we have limited ways of doing documentation for the SDK's, I would suggest to not add that function and to wait that MeiliSearch core adds it.

Meanwhile, in cases where the behavior needs to meet the user's need, the user will implement it the way he wants it.

**Comment by curquiza** [comment]
> The best practice would have been that the function exists in MeiliSearch core and that it is handled with a transaction.

Totally agreed!

Since this method is not asked by our users (like `getOrCreateIndex`) I close this issue. The `deleteAllIndexes` method is really useful for the SDK tests, but this discussion makes us relize this method is not that much useful for a concrete use-case, especially because we don't really know what our users expect as behavior.
The method is already implemented in PHP, so we won't delete it, but I'm going to delete the corresponding issues in the SDKs repositories.

If someone reading this wants to re-open the issue because they needs it in their project, let us know 🙂 We are open to discussion.
