### ISSUE TITLE
Be explicit about the fact that adding/updating documents and settings update are asynchronous

### ISSUE THREAD

**Issue by gmourier** [meilisearch/integration-guides#140]
We've seen a lot of feedback from people who don't understand that the writing operations are asynchronous.

A first idea would be to make this more explicit in the README.md. In the getting started, just after the first code example, we inform that we can find the update details from the `updateId`. It does not seem sufficient to give the knowledge of this asynchronous behavior. It could also be placed in a more prominent place, where the reader's attention starts. 

Why not in the code example as a comment or before the first code example with something like:

🤓 Adding/Updating documents and settings update are asynchronous operations by design. This means that the received response does not guarantee instant writing of the data.
If you want to know when a writing operation is finished,  you should check the status of the update from the `updateId` given in the response or use the waitForUpdate. See how to [get an update status](https://dev.docs.meilisearch.com/reference/api/updates.html#get-an-update-status) API reference.
If you want to wait for a writing operation to finish, you can use the `waitForPendingUpdate` method.

A second idea, more difficult to implement, would be to rename the methods with something like `asyncAddDocuments`. The term `async` here may not be the best choice, but if the right term is found it would allow knowledge to be shared directly in the naming of the methods.

**Comment by curquiza** [comment]
Thanks for your feedback 😁

There is only a small sentence after the first example for two reasons:
- it's the getting started section, in a README: we wanted to make it easy to use, with examples, and not to overwhelm the users with too much text. From our point of view, the getting started experience in the README should be quick and not to afraid the user.
- We did not want to talk about asynchronous tasks here since it's a complex concept. We even chose to not put the word "asynchronous" to avoid the users being afraid of this complicated word (a user told us he's scared of the asynchronous tasks since he used Elastic and it was a mess 😂)

But we can reconsider it, what do you think @bidoubiwa, @alallema? 🙂

**Comment by alallema** [comment]
If there is a lot of feedback from users I think it's worth talking about it again.

**Comment by brunoocasali** [comment]
I don't expect this to change shortly. Also, our documentation evolved significantly in the last few months, so I'll close this issue. If you think I'm mistaken, let me know!
