### ISSUE TITLE
Update code-sample on document routes

### ISSUE THREAD

**Issue by alallema** [meilisearch/integration-guides#156]
Following the documentation issues (https://github.com/meilisearch/documentation/issues/1213) and PR (https://github.com/meilisearch/documentation/pull/1242) we should add the code sample related to `add_or_replace_documents` and `add_or_update_documents` with the optional `primaryKey` parameter and modify the `add_or_update_documents_1`.

### Addition of code-sample

**code-sample-id**: `add_or_replace_documents_with_primaryKey_1`

**code-sample example in curl**:
```bash
  curl \
    -X POST 'http://localhost:7700/indexes/movies/documents?primaryKey=reference_number' \
    -H 'Content-Type: application/json' \
    --data-binary '[{
        "reference_number": 287947,
        "title": "Shazam",
        "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
        "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
        "release_date": "2019-03-23"
     }]' 
```

**code-sample-id**: `add_or_update_documents_with_primaryKey_1`

**code-sample example in curl**:
```bash
  curl \
    -X PUT 'http://localhost:7700/indexes/movies/documents?primaryKey=reference_number' \
    -H 'Content-Type: application/json' \
    --data-binary '[{
        "reference_number": 287947,
        "title": "Shazam",
        "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
        "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
        "release_date": "2019-03-23"
     }]'  
```

### Modification of code-sample

**code-sample-id**: `add_or_update_documents_1 `

```bash
  curl \
    -X PUT 'http://localhost:7700/indexes/movies/documents' \
    -H 'Content-Type: application/json' \
    --data-binary '[{
        "reference_number": 287947,
        "title": "Shazam ⚡️",
        "genres": "comedy"
    }]'
```

FYI, the dotnet SDK does not have its code-samples up to date.

**Comment by bidoubiwa** [comment]
The @meilisearch/docs-team is considering moving these examples to the [document core-concept](https://docs.meilisearch.com/learn/core_concepts/documents.html) as these examples are very niche (need confirmation @dichotommy). 

Through the stats of MeiliSearch we saw that 99% of the users datasets have a primary-keys containing `id`. 

The problem with the example above is that it implies that the `primaryKey` should always be passed as a parameter. After talking with @dichotommy we came to the conclusion (i think you should confirm @dichotommy) that examples in the API reference should be simple and directed to the biggest use case.

**Comment by dichotommy** [comment]
Thank you @bidoubiwa 🙏🏻 

We on the @meilisearch/docs-team feel that as long as adding documents with a primary key is an option, it should be documented with a code sample (the same logic can and will be applied to a lot of other endpoint parameters at some point).

The question for us is how the code sample demonstrating the `primaryKey` parameter should be integrated into the docs. Initially we thought we would add it to the API reference for the [add documents](https://docs.meilisearch.com/reference/api/documents.html#add-or-replace-documents) and [update documents](https://docs.meilisearch.com/reference/api/documents.html#add-or-update-documents) endpoints. However, @bidoubiwa correctly pointed out that our API reference currently adheres to the rule of "one endpoint, one example". It would be a shame to sacrifice this consistency without considering it further.

@bidoubiwa 's proposed solution is to integrate the new code samples in the [documents guide](https://docs.meilisearch.com/learn/core_concepts/documents.html) instead, so that at least the parameter is documented somewhere. I also support this. This will require redoing [the PR](#1242) and may result in changes to the code samples, so **I would recommend that the @meilisearch/integration-team waits before implementing on their side**. Thanks! ❤️

**Comment by curquiza** [comment]
Ok, so let's close this issue until the @meilisearch/docs-team team takes a definitive decision with https://github.com/meilisearch/documentation/pull/1242.
Once this PR is merged, the integration team will re-open an issue according to the latest changes.
