### ISSUE TITLE
LInk to elixir SDK

### ISSUE THREAD

**Issue by alec-c4** [meilisearch/integration-guides#240]
Hi,
I've found that you haven't added a link to Elixir SDK, here is it - https://github.com/robottokauf3/meilisearch-elixir

**Comment by brunoocasali** [comment]
Hi @alec-c4 how are you?

We do not maintain this SDK, and I have in the past created an issue suggesting my time to help improve the SDK (here https://github.com/robottokauf3/meilisearch-elixir/issues/10). Unfortunately, the maintainer did not reply, and the project needs updates to support the latest versions of Meilisearch.

Also, since we don't maintain it officially, I added it to our [awesome-meilisearch] (https://github.com/meilisearch/awesome-meilisearch) repo.

In any case, are you currently using elixir with Meilisearch, and are you using this SDK? Knowing that the users need an SDK in a particular language like Elixir helps us make decisions to create those SDKs.
