### ISSUE TITLE
MeiliSearch changes process

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#29]
## MeiliSearch Changes Process

When MeiliSearch introduces a new change in their API design we should be involved and aware.
Those changes could potentially imply changes or new features that should be added to the clients.

To ensure the flow of information a process should be made and applied. We want to avoid unnecessary complexity. 

This is a draft of what the process could be:

## Process Draft

1. A new change is introduced in the HTTP API of MeiliSearch
2. A tracking issue should exist in which the integration team is pinged, and a label is added `http-changes` (?)
3. We discuss and approve the usage or the changes 🚀
4. An issue is made in this repository (`integration-guides`) in which we discuss how it will be implemented in the SDK's
5. We discuss and approve the usage or the changes 🚀
6. Issues are made in each SDK concerning that change/feature. **With the right labels**. 
7. If no meilisearch-bump branch exists in this SDK, it is created with the following name: `bump-meilisearch-v0.*.*`. The version is the one from MeiliSearch in which that change/feature will be added
8. The pull requests that solves that issue points to the bump-meilisearch branch
9. At least one person of the integration team should review that PR before it is merged into the bump branch

### MeiliSearch Questions
- Should we be kept aware via more direct communication? (Slack,..?)

### SDK's questions
- ~What are the right labels to add to the issue that are made in each SDK?~
=> `integration-guide` `xxx-SDK` + for example `MeiliSearch bump` ?
- ~Should it be added to the projects?~ **Yes**
- ~Should the issues in the SDK's but also in the integration guide have a specific naming in the name? ex: `MeiliSearch Changes: Search Method is now POST and not GET`. Or should it instead have a specific label `meilisearch-changes` or something like that~
No, `MeiliSearch bump` label added

Need an opinion from @Kerollmops @MarinPostma @curquiza @eskombro  @tpayet 

# FINAL DECISION FOR THE PROCESS
(edit by @curquiza)

1. A new change is introduced in the HTTP API in the MeiliSearch repository:
  - If it's a quick fix with no linked issue: only a PR is available and this PR should be tagged as `meilisearch-http` by the core-engine team
  - If it's a new feature or a fix with an existing issue: this issue should be tagged as `meilisearch-http`. The core-team (and the SDK team if needed) discusses the final decision **in this issue** so that everyone is kept informed.
2. The core-engine team adds the PR/issue to the [MeiliSearch Milestones](https://github.com/meilisearch/MeiliSearch/milestones).
3. If the MeiliSearch issue/PR involves any change for the SDKs, an issue is made in this repository (`integration-guides`) in which we discuss how it will be implemented in the SDKs. The issue should be tagged as `MeiliSearch bump`.
4. We discuss and approve the usage or the changes (the 🚀 emoji means an approval)
5. Issues are made in each SDK concerning that change/feature with the `MeiliSearch Bump` label (**this step should be automatized!!**)
6. If no `meilisearch-bump-vX.X.X` (X.X.X = next MeiliSearch version) branch exists in this SDK repository, we have to create one.
7. The pull requests that solves that issue points to the `bump-meilisearch-vX.X.X` branch and should be reviewed before merging. **Be aware about breaking changes: a `breaking-change` label should be added to the PR if it is!**
8. Once all the changes are merged into `meilisearch-bump-vX.X.X`, a final review is done by an SDK team member before being merged into `master`.
9. We can now publish the current draft release (generated automatically) as the new release!

**Comment by curquiza** [comment]
> Should we be kept aware via more direct communication? (Slack,..?)

A label `Integration team required` or another label name can be added to the tracking issue, because all tracking issues do not imply changes in our side.

> What are the right labels to add to the issue that are made in each SDK?

 I'm not sure to understand

> Should the issues in the SDK's but also in the integration guide have a specific naming in the name? ex: MeiliSearch Changes: Search Method is now POST and not GET. Or should it instead have a specific label meilisearch-changes or something like that

I like the idea. Adding a label is enough from my POV because we can see it clearly in the issues list (with its specific coloration). Better than in the title.
I suggest `MeiliSearch bump` as label name.

**Comment by eskombro** [comment]
> Should we be kept aware via more direct communication? (Slack,..?)

It would be interesting. But at least we can set the "minimum", by labeling or pinging in GitHub, seems a good process.

> What are the right labels to add to the issue that are made in each SDK?

Do you mean like for example a v0.X.X label? Or what other label can be used, something like "integration-guides issue"? "Core change"?

For me it is enough with the labeling as we are doing now, and linking the `integration-guides` issue in the description if it is the implementation of something we discussed there. But if you have any idea that would make it better for you, I'm totally open :)

> Should it be added to the projects?

Yeah!
(I basically add every issue unless it is some idea/discussion/question, not implementation)

> Should the issues in the SDK's but also in the integration guide have a specific naming in the name? ex: MeiliSearch Changes: Search Method is now POST and not GET. Or should it instead have a specific label meilisearch-changes or something like that

We can use milestones or keep using just labels. I don't think we need to name it in a precise way.

We can define sometime some issues/branches naming guidelines if we all find a good guideline, to encourage best practices, but that's probably another discussion

**Comment by eskombro** [comment]
Also, @bidoubiwa, in my understanding, the labels `need opinion`, `need clarification` and `need approval` shouldn't be used together (as in the issue). The idea is that those are different `states` of an issue to know where we are at. So it's confusing for me to see the 3 of them in the same issue. But maybe it's just me

**Comment by bidoubiwa** [comment]
> What are the right labels to add to the issue that are made in each SDK?

I meant the ones we already add :
`integration-guide` `xxx-SDK` + for example `MeiliSearch-bump` ?

> Should the issues in the SDK's but also in the integration guide have a specific naming in the name? ex: MeiliSearch Changes: Search Method is now POST and not GET. Or should it instead have a specific label meilisearch-changes or something like that

I like `MeiliSearch bump` as a label. What do you think eskombro?

**Comment by curquiza** [comment]
> I meant the ones we already add :
> integration-guide xxx-SDK + for example MeiliSearch-bump ?

I understand now! 🙂 Yes, I like your `MeiliSearch Bump`, but it should be added by a bot 😉 (you know us...)

**Comment by MarinPostma** [comment]
While I agree that we need tracking issues for the sdk team to be involved in the process of feature creation, we also have plenty of issue that do not fit in this process, such as bug fixes and enhancement. They do not require a tracking issue (we need to keed our process kinda lightweight I think we all agree). If such PR change things to what meilisearch exposes, SDK team must be notified, and discussing minor detail in the PR must be sufficient. I understood that we can @ groups now, let's use this.

Also, everybody is involved in tracking issues, because by definition they  change the way meili work and discussion is required, so I don't think we need anything else but an `approved` tag once we all agree on the changes (as far as the core team is concerned).

Lastly, maybe tracking issues really should be milestone, tracking all issues and PR related to the feature at hand. Then we would know what's left to do for each tracking issue?

**Comment by curquiza** [comment]
> While I agree that we need tracking issues for the sdk team to be involved in the process of feature creation, we also have plenty of issue that do not fit in this process, such as bug fixes and enhancement. They do not require a tracking issue

Totally agree with the fact that all the changes concerning the HTTP are not "tracking issues". That's why we suggest using a new label in MS repo -> `http-changes` so that we can filter them easily.

**Comment by MarinPostma** [comment]
So every PR must be linked to an issue?

**Comment by eskombro** [comment]
@MarinPostma I like the @group idea, We don't have a "SDK" group (but we should)

**Comment by tpayet** [comment]
> So every PR must be linked to an issue?

It seems reasonnable to expect an issue when we are developing a feature, or when the API change. If it's a hotfix, it is not necessary. 
We can schedule a call this afternoon if anything is unclear to anyone

**Comment by Kerollmops** [comment]
I think that tracking issues are necessary when we introduce a new feature and not when we do a fix, however we must discuss bug fixes somewhere and I think the PR itself is enough (Slack can obviously be used to have a more direct discussion).

The `meilisearch-version-bump` label is not necessary because we will use [the milestones](https://github.com/meilisearch/MeiliSearch/milestones) (as Marin and Quentin remind me about their existence 😂) and its the best way to track the progress of a MS version bump. The milestone will be named after the version number prefixed by a `v` (i.e. `v0.11.1`).

I like the idea of the `http-changes` label too, however I am not sure it is the best way to inform the integration and documentation team about changes to the HTTP interface. Combining this label on tracking issues with a ping to the @ integration team can be sufficient to keep a good work flow maybe.

**Comment by eskombro** [comment]
The problem with discussin in PRS is that ofte we end up discussing about an implementation that has already be done, instead of dicussing before it is implemented. But if we do a draft PR and make the discussion there, for me that would be enough as @Kerollmops says!

**Comment by curquiza** [comment]
> I like the idea of the http-changes label too, however I am not sure it is the best way to inform the integration and documentation team about changes to the HTTP interface. Combining this label on tracking issues with a ping to the @ integration team can be sufficient to keep a good work flow maybe.

Without the label, I cannot filter them in the MeiliSearch GH issues. Plus, this label could be added to the issues reported as bug as well by users -> really useful!
For me, the ping is not really necessary because it can be lost in the issue conversation, but not the label.

From my POV discussing in PR is not convenient at all! I don't want to check issues AND PR when I'm starting to code my SDK...

**Comment by MarinPostma** [comment]
> From my POV discussing in PR is not convenient at all.. I don't want to check issues AND PR when I'm starting to code my SDK...

Very often small bugs are fix when they are found, as part of other PR, such as #792. Writing issues for these is just workflow breaking IMO, and is not worth it. Also you won't have to check PR as we will tag the sdk/integration teams when their input is needed + you can filter PR and issues together by removing the is:issue filter in the search :)

**Comment by MarinPostma** [comment]
And we'll probably not nail this process the first time around, let's keep it simple, and address issues as they come by :)

**Comment by curquiza** [comment]
Final decision for the communication between the core team and SDKs team:
- the MeiliSearch repo is going to use the [GitHub Milestones](https://github.com/meilisearch/MeiliSearch/milestones) so that the SDK team can easily check what is going to be in the next version (related to the API or not)
- the core-engine team will add the `meilisearch-http` (that already exists on the MS repo) to every issue and PR that are related to a change in the HTTP part. A PR/issue with this label might indeed concern the SDK team (and the docs team btw). If the SDK team realizes this issue/PR would involve changes in the SDKs, an issue on this repo (integration-guides) will be created with a link to the corresponding MeiliSearch issue/PR.
- For the Slack communication: a GH bot can easily be configurated individually if you want to be ping each time an issue/PR is tagged with `meilisearch-http`

**Comment by curquiza** [comment]
I've updated the main description of the issue with the Final Decission Process.

**Comment by curquiza** [comment]
@bidoubiwa @eskombro Do you approve the new process I wrote in the description of the issue?
If you are, I'm going to create a markdown file in the repo instead of keeping this issue open 🙂

(If you need to fix some English sentences you will do it in my future PR. Be sure here you agree with the different steps)

**Comment by bidoubiwa** [comment]
> If the MeiliSearch issue/PR involves any change for the SDKs, an issue is made in this repository (integration-guides) in which we discuss how it will be implemented in the SDKs.

Shouldn't we add the `MeiliSearch Bump` tag to the issue made in `integration-guide` aswell ?

**Comment by curquiza** [comment]
I think that's a good idea! I'm updating that!

**Comment by curquiza** [comment]
I pass this issue as `ready to implement` since everyone agrees.

Implementation = add a file in this repo explaining the different steps I wrote in the issue description. Someone has to do a PR that the others are going to review 🙂

**Comment by curquiza** [comment]
The pre-release week process is described here: https://github.com/meilisearch/integration-guides/blob/main/guides/pre-release-week.md
