### ISSUE TITLE
README header links

### ISSUE THREAD

**Issue by qdequele** [meilisearch/integration-guides#57]
I would like to add on all readme two things. The first one is the public [roadmap](https://roadmap.meilisearch.com/), and the second one is the [sandbox](http://sandbox.meilisearch.com/).

**Comment by curquiza** [comment]
I agree, this kind of information is important. 

The current header looks like this:
<img width="614" alt="Capture d’écran 2020-11-12 à 09 54 45" src="https://user-images.githubusercontent.com/20380692/98917936-4b96c600-24cd-11eb-80ec-221c2f398aba.png">

Maybe adding two other information would be a little bit "heavy".
Don't you think we should also remove some of the current header titles? So, we can add the roadmap and the sandbox and the users could better see them.
Or maybe someone wants to suggest another display?

**Comment by bidoubiwa** [comment]
We could add the sandbox in the `Run MeiliSearch` category and add Roadmap in the headings. 
About the headings to remove, I think `blog` and `twitter` should not be there. But mostly twitter if we do not want to remove everything.

When looking at some other repos this is what they have in their heading: 

### Algolia

<img width="820" alt="Screenshot 2020-11-12 at 10 23 09" src="https://user-images.githubusercontent.com/33010418/98921233-53f10000-24d1-11eb-9d96-c61c43913117.png">
 
### Stripe : No headings 

### Strapi: Completely different

<img width="696" alt="Screenshot 2020-11-12 at 10 25 41" src="https://user-images.githubusercontent.com/33010418/98921356-7daa2700-24d1-11eb-8ae3-a8d9de238b5b.png">

### [Armory](https://github.com/armory3d/armory) 

<img width="879" alt="Screenshot 2020-11-12 at 10 31 43" src="https://user-images.githubusercontent.com/33010418/98922055-4ee08080-24d2-11eb-967a-ae0ee9288db1.png">

### [Nuxt JS](https://github.com/nuxt/nuxt.js)
<img width="379" alt="Screenshot 2020-11-12 at 10 37 38" src="https://user-images.githubusercontent.com/33010418/98922749-21480700-24d3-11eb-8490-092b62f7e388.png">

Based on the fact that no one has a clear idea of what to add on their Readme, I would suggest we do it how we think its best. 

I suggest the following: 
- MeiliSearch
- Documentation
- RoadMap
- Website 
- FAQ
- Community Slack

**Comment by curquiza** [comment]
> We could add the sandbox in the Run MeiliSearch category and add Roadmap in the headings.

Agreed!

> I suggest the following:
> 
>     * MeiliSearch
> 
>     * Documentation
> 
>     * RoadMap
> 
>     * Website
> 
>     * FAQ
> 
>     * Community Slack

I'm not sure to understand what you suggest exactly, to keep the same headers display we have right now?
The comparison with strapi and nuxt is not really relevant for our SDKs READMEs: they correspond more to the MeiliSearch repo than to our SDK repos.
And the slack link is already added in the badges, thanks to the slack logo it's easier to spot it from my POV:

<img width="662" alt="Capture d’écran 2020-11-12 à 11 07 57" src="https://user-images.githubusercontent.com/20380692/98926242-57878580-24d7-11eb-84f3-e2eecdada350.png">

Otherwise, the order you sugggest is good to me 🙂

**Comment by qdequele** [comment]
I prefer, for things that matter, like links we want to put forward, a vertical reading. 

So we could keep for each repository their specific tools label on top: 

[ Build | Passing ] [ Report | A+ ] [ License | MIT ] [ BORS | enabled ] [ Codecov | 100% ]

And add under that, some links like Nuxt does:

- ⚙️ MeiliSearch
- 📘 Documentation
- 📌 Roadmap
- 🕹 Sandbox
- 💬 Slack

What do you think?

**Comment by bidoubiwa** [comment]
It might be more visible:

<img width="1066" alt="Screenshot 2020-11-17 at 10 18 20" src="https://user-images.githubusercontent.com/33010418/99370722-5501a300-28be-11eb-992b-529452173b04.png">

I'm not sure which one I prefer

**Comment by curquiza** [comment]
I don't really like (from my POV) the list of links because I want the users to see asap the Getting Started with less scroll as possible.

As a first version, I'm going to add the roadmap to the headers in a really simple way (between "Documentation" and "Website").
Then, as a second step, I'm going to organize a meeting to discuss together the improvements 🙂
The goal of doing two steps is to integrate as quickly as possible the roadmap link in the READMEs, and then, spend time on presentation details.

About the sandbox: since the sandbox cannot welcome more than 21 users, I'm not going to update all the README with it for the moment.

**Comment by curquiza** [comment]
The simple version was implemented. If we need a better header, we will reopen an issue.
