### ISSUE TITLE
Add Codecov for all repositories 

### ISSUE THREAD

**Issue by qdequele** [meilisearch/integration-guides#59]
[Codecov](https://codecov.io/) is already used in [MeiliSearch](https://codecov.io/gh/meilisearch/MeiliSearch), it helps us to know if a PR add non-tested code. If it's the case, we don't accept the PR. It's easy to install, easy to configure. Don't hesitate to ping me if you need help. 

- [x] Python
- [ ] PHP
- [ ] Ruby
- [ ] JS
- [ ] Rails
- [ ] Symfony
- [ ] Go
- [ ] C#
- [ ] Dart
- [ ] Swift
- [ ] Java

**Comment by fharper** [comment]
I love that!

**Comment by curquiza** [comment]
@bidoubiwa? We need your approval so that I can try it on one repo

**Comment by bidoubiwa** [comment]
Great!

**Comment by curquiza** [comment]
FYI, on the core team side, we removed the trigger of CodeCoverage to every PR since we felt it more like a spam rather than a real report.
We still can trigger CodeCoverage on the MeiliSearch repo, but manually, see our yml config: https://github.com/meilisearch/MeiliSearch/blob/main/.github/workflows/coverage.yml

Maybe a manual trigger (or a cron) would be better rather than a trigger on each PR.
WDYT?

**Comment by brunoocasali** [comment]
I would love to see this implemented in all the SDKs, but unfortunately, we will not have time to work on this for the next months. I'll appreciate it if people from the community do it :)

**Comment by brunoocasali** [comment]
All the issues were created in the correspondent repositories!
