### ISSUE TITLE
Create Heroku integration

### ISSUE THREAD

**Issue by fharper** [meilisearch/integration-guides#66]
I guess it's the equivalent of what we have done on DO: https://elements.heroku.com/buildpacks

**Comment by curquiza** [comment]
Is this issue the same requirement than in this discussion?
https://github.com/meilisearch/MeiliSearch/discussions/1092

**Comment by fharper** [comment]
I assume the Heroku button is using the buildpack, but it's more like having MeiliSearch when you search the Heroku "marketplace". Like we've done with DO

**Comment by tpayet** [comment]
As far as I understand on Heroku there are add-ons, buttons or buildpacks. These different things are called [Heroku elements](https://elements.heroku.com).

Buildpacks are similar to preset environment in which you would be able to deploy a Node.js app or a Rust app. But there is no service up

Buttons are complete application such as an Rails app or an Express app that you can run within a buildpack. MeiliSearch used to have a button but application must be stateless since the file storage is non-persistent, hence the [previous discussion](https://github.com/meilisearch/MeiliSearch/discussions/1092).

Finally, add-ons are services you can run along your app to extend it. This is where we can find databases such as PostgreSQL or monitoring tool. This is also where we can find Elastic-on-the-go so this is where MeiliSearch should be present. 

## Conclusion
I believe we want to build an Heroku addon and here is a tutorial: https://devcenter.heroku.com/articles/building-an-add-on.

**Comment by fharper** [comment]
Oh, thanks for the clarification @tpayet, I thought they were named buildpack!

TIL :)

**Comment by brunoocasali** [comment]
This issue was created before we had a perfect way of managing Meilisearch instances. You should check out the https://www.meilisearch.com/cloud ;)

Based on that, there is no point of working in the Heroku integration right now!
