### ISSUE TITLE
Should searchParameters in SDK's put wild cards inside an array ?

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#86]
When performing a search on meilisearch, using the `POST` route when using wildcards, we need to wrap it inside a array.

Example: 

JS: 
```javascript
attributesToRetrieve: ['*']
```

PHP
```php
 'attributesToRetrieve' => ['*'],
```

My question is, given that it is a nonintuitive behavior ( at least for me), should we not replace them by as simple `*` as shown below:

JS: 
```javascript
attributesToRetrieve: '*'
```

PHP
```php
 'attributesToRetrieve' => '*',
```

**Comment by curquiza** [comment]
`[*]` is the behavior of MeiliSearch.
Plus for me, it's non-intuitive to have a field that could take both types: a string (with `*`) or an array (`['title', 'author']`).
And what would we do when there is only one attribute: should we write `title` or `['title']`? 
The behavior becomes ambigous.
From my POV, it's more intuitive to always have the same type when you code: array or string. Not both. So for me, accept the simple `*` is non-intuitive.

**Comment by curquiza** [comment]
After an internal meeting, we concluded that letting the possibility to use either the string or the array (containing a single string) could be helpful and intuitive for the user.
Indeed, people like me thinking this is not intuitive will use the array, and the other could also use the string.

However, here are the following tests we should validate (and add to the test suite) if implementing this possibility:
- it works with a single string as a wildcard: `"*"` sends a `["*"]` to the MeiliSearch server
- the `["*"]` behavior still works
- it works with a single string as an attribute: `"title"` sends a `["title"]` to the MeiliSearch server
- the `["title"]` behavior still works
- the `["title", "author"]` behavior still works

⚠️ All these tests should be done for `attributesToRetrieve`, `attributesToCrop` and `attributesToHighlight`, otherwise the behavior is not consistent.

**Comment by curquiza** [comment]
Closing this issue in favor of #88 where I detailed the steps and the concerned repos in the main description of the issue.!
