### ISSUE TITLE
Body in POST search: allow passing a string instead of an array if only one attribute

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#88]
When performing a search on MeiliSearch, using the `POST` route when using wildcards, we need to wrap it inside an array.

Example: 

```javascript
{
  attributesToRetrieve: ['*']
}
```

We could let the possibility to the user to write only:

```javascript
{
  attributesToRetrieve: '*'
}
```

but the previous possibility will still available!

--------------

Here are the following tests we should validate (and add to the test suite) if implementing this possibility:
- it works with a single string as a wildcard: `"*"` sends a `["*"]` to the MeiliSearch server
- the `["*"]` behavior still works
- it works with a single string as an attribute: `"title"` sends a `["title"]` to the MeiliSearch server
- the `["title"]` behavior still works
- the `["title", "author"]` behavior still works

⚠️ All these tests should be done for `attributesToRetrieve`, `attributesToCrop` and `attributesToHighlight`, otherwise the behavior is not consistent.

This implementation only concerns repositories containing a `search()` method (so the SDKs) and where this kind of behavior is still idiomatic.

<s>- [ ] meilisearch-dart</s>
<s>- [ ] meilisearch-dotnet</s>
<s>- [ ] meilisearch-go</s>
<s>- [ ] meilisearch-java</s>
- [ ] meilisearch-js
- [ ] meilisearch-php
- [ ] meilisearch-python
- [ ] meilisearch-ruby
<s>- [ ] meilisearch-rust</s>
- [ ] meilisearch-swift

Feel free to mention if you don't think this is relevant to implement this in one of the listed repositories.

💡 This kind of behavior could be also relevant when updating the settings (ex: for `searchableAttributes` or `displayedAttributes`) but I think the setting updates are less  used than the search, so let's focus on this issue first.

_following this discussion https://github.com/meilisearch/integration-guides/issues/86_

**Comment by eskombro** [comment]
I may be missing something, but I think this is not really wanted/achievable in strongly typed languages (Ok, maybe TS will accept this, I'm guessing) since we need to define a Type in a structure, and this can not be a string or an array of strings at the same time. In this cases, Go and Java implementation assume array of strings. I'm guessing Rust could use an `Option`. What do you think about this?

**Comment by curquiza** [comment]
I agree this would not be really relevant for strongly typed language. Rust can do it (we talked about it with Kero today) so I think this is mostly doable in most language.
However, even if it's doable I'm not sure this is expected behavior for Go, Java, Dotnet or Rust users.
I think this might be relevant for python, PHP, ruby and JS users mostly.

**Comment by eskombro** [comment]
I agree JS, Python, Ruby, and PHP can easily implement/test this behavior, and users would probably be familiar with it!

Personally for Go and Java, I think this introduces unnecessary complexity, since the way I see it the solution will be just finding a workaround to the typing conflict, and probably one that the user isn't even expecting to find :)

**Comment by bidoubiwa** [comment]
It's a lot of maintenance and also hard to implement in a lot of typed languages. I would say no.

**Comment by alallema** [comment]
Same for me. I would say no too

**Comment by curquiza** [comment]
Ok! Closing this issue!
